# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mu9cRJHrKLNXoOYF6v848Og5AXMU8g1F
"""

import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

np.random.seed(42)

rows = 1000

price = np.random.randint(80, 150, rows)
cost = np.random.randint(50, 100, rows)
season = np.random.uniform(0.8, 1.2, rows)
competitor = np.random.randint(75, 155, rows)

demand = 200 - 0.7*price + 0.4*competitor + 25*season + np.random.normal(0, 8, rows)
profit = (price - cost) * demand

data = pd.DataFrame({
    "price": price,
    "cost": cost,
    "season_factor": season,
    "competitor_price": competitor,
    "demand": demand,
    "profit": profit
})

"""data.to_csv("business_data.csv", index=False)

print("Dataset created successfully!")"""

data=pd.read_csv("business_data.csv")
print(data.head())
print(data.info())
print(data.describe())

DATA_PATH = "business_data.csv"
def clean_datd(df):
    required_columns=["price","cost","season_factor","competitor_price","demand","profit"]
    if not all(col in df.columns for col in required_columns):
        raise ValueError(f"Dataset must contain: {required_columns}")
    df = df.drop_duplicates()
    for col in required_columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")
    df = df.dropna(subset=required_columns)
    df = df[
            (df["price"] > 0) &
            (df["cost"] >= 0) &
            (df["competitor_price"] > 0) &
            (df["season_factor"] > 0) &
            (df["demand"] >= 0)
        ]
    df["profit"] = (df["price"] - df["cost"]) * df["demand"]
    def remove_outliers(data, column):
        Q1 = data[column].quantile(0.25)
        Q3 = data[column].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        return data[(data[column] >= lower) & (data[column] <= upper)]

    for col in required_columns:
        df = remove_outliers(df, col)

    if df.empty:
        raise ValueError("Dataset empty after cleaning. Check data quality.")
    return df

df = pd.read_csv(DATA_PATH)
df = clean_datd(df)

X = df[['price', 'season_factor', 'competitor_price']]
y = df['demand']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)

print("\nModel Performance")
print("------------------")
print("R2 Score:", round(r2, 4))
print("Intercept:", round(model.intercept_, 4))
print("Coefficients (price, season_factor, competitor_price):",
      [round(c, 4) for c in model.coef_])
joblib.dump(model, "demand_model.pkl")

def predict_demand(price, season_factor, competitor_price):
    """
    Predict demand based on:
    - price
    - season factor
    - competitor price
    """
    input_data = np.array([[price, season_factor, competitor_price]])
    predicted = model.predict(input_data)
    return float(predicted[0])

"""Plot graph"""

import matplotlib.pyplot as plt

y_pred = model.predict(X_test)

plt.figure()
plt.scatter(y_test, y_pred)

plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()]
)

plt.xlabel("Actual Demand")
plt.ylabel("Predicted Demand")
plt.title("Linear Regression: Actual vs Predicted Demand")

plt.show()

import numpy as np
import matplotlib.pyplot as plt

mean_season = df['season_factor'].mean()
mean_comp = df['competitor_price'].mean()

lower_bound = df['price'].quantile(0.05)
upper_bound = df['price'].quantile(0.95)

price_range = np.linspace(lower_bound, upper_bound, 200)

X_plot = np.column_stack([
    price_range,
    np.full(200, mean_season),
    np.full(200, mean_comp)
])

predicted_demand = model.predict(X_plot)

df_filtered = df[
    (df['price'] >= lower_bound) &
    (df['price'] <= upper_bound)
]

plt.figure()

plt.scatter(df_filtered['price'], df_filtered['demand'], alpha=0.3)
plt.plot(price_range, predicted_demand, linewidth=3)

plt.xlabel("Price")
plt.ylabel("Demand")
plt.title("Polynomial Regression (Trimmed Range)")

plt.show()

cost = float(input("Enter Cost: "))

# Prompt user for specific values for prediction
input_price = float(input("Enter Price for prediction: "))
input_season_factor = float(input("Enter Season Factor for prediction: "))
input_competitor_price = float(input("Enter Competitor Price for prediction: "))

# Call predict_demand with scalar input values
predicted_demand = predict_demand(input_price, input_season_factor, input_competitor_price)
predicted_profit = (input_price - cost) * predicted_demand

print("\nPredicted Demand:", round(predicted_demand, 2))
print("Estimated Profit:", round(predicted_profit, 2))